/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.19.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { Coin } from "@cosmjs/amino";
import { MsgExecuteContractEncodeObject } from "cosmwasm";
import { MsgExecuteContract } from "cosmjs-types/cosmwasm/wasm/v1/tx";
import { toUtf8 } from "@cosmjs/encoding";
import { InstantiateMsg, ExecuteMsg, SetStatusMsg, Addr, QueryMsg, AllowanceResponse, Status, StatusResponse } from "./Blacklist.types";
export interface BlacklistMessage {
  contractAddress: string;
  sender: string;
  setStatus: ({
    status
  }: {
    status: SetStatusMsg;
  }, funds?: Coin[]) => MsgExecuteContractEncodeObject;
}
export class BlacklistMessageComposer implements BlacklistMessage {
  sender: string;
  contractAddress: string;

  constructor(sender: string, contractAddress: string) {
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.setStatus = this.setStatus.bind(this);
  }

  setStatus = ({
    status
  }: {
    status: SetStatusMsg;
  }, funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          set_status: {
            status
          }
        })),
        funds
      })
    };
  };
}