/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.10.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Addr = string;
export type Uint128 = string;
export interface Donor {
  addr: Addr;
  nickname?: string | null;
  total_campaign_donations: Uint128;
  total_general_donations: Uint128;
  validator_link?: Link | null;
  [k: string]: unknown;
}
export interface Link {
  label: string;
  url: string;
  [k: string]: unknown;
}
export type ExecuteMsg = {
  add_campaign: {
    campaign_address: string;
    campaign_name: string;
    [k: string]: unknown;
  };
} | {
  disable_campaign: {
    campaign_name: string;
    [k: string]: unknown;
  };
} | {
  receive: Cw20ReceiveMsg;
} | {
  fund: FundMsg;
} | {
  update_config: {
    cw20_donation_token_address?: string | null;
    general_fund_address?: string | null;
    native_token_denom?: string | null;
    spark_token_contract_address?: string | null;
    [k: string]: unknown;
  };
} | {
  update_nickname: {
    nickname?: string | null;
    [k: string]: unknown;
  };
} | {
  update_validator_link: {
    validator_link?: Link | null;
    [k: string]: unknown;
  };
};
export type Binary = string;
export type FundMsg = {
  fund_general: {
    donor_address_type: AddressType;
    [k: string]: unknown;
  };
} | {
  fund_campaign: {
    campaign_name: string;
    donor_address_type: AddressType;
    [k: string]: unknown;
  };
};
export type AddressType = "Private" | "Validator";
export interface Cw20ReceiveMsg {
  amount: Uint128;
  msg: Binary;
  sender: string;
  [k: string]: unknown;
}
export interface InstantiateMsg {
  cw20_donation_token_address?: string | null;
  general_fund_address: string;
  native_donation_token_denom: string;
  spark_token_contract_address: string;
  [k: string]: unknown;
}
export type Status = "active" | "inactive";
export interface QueryGetCampaignResponse {
  campaign: Campaign;
  [k: string]: unknown;
}
export interface Campaign {
  address: Addr;
  id: number;
  name: string;
  status: Status;
  total_donations: Uint128;
  [k: string]: unknown;
}
export interface QueryGetDonorResponse {
  donor: Donor;
  [k: string]: unknown;
}
export type QueryMsg = {
  query_total_donated: {
    [k: string]: unknown;
  };
} | {
  query_get_campaign: {
    campaign_name: string;
    [k: string]: unknown;
  };
} | {
  query_get_donor: {
    donor_address: string;
    [k: string]: unknown;
  };
};
export type QueryTotalDonatedResponse = string;